// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAtVvBbYaaRHIaafeTBJ1NteSSohLyIO4',
    appId: '1:151968151208:web:fe9091ca9a9ca6d01ff49d',
    messagingSenderId: '151968151208',
    projectId: 'socialfeed-95b3b',
    authDomain: 'socialfeed-95b3b.firebaseapp.com',
    storageBucket: 'socialfeed-95b3b.firebasestorage.app',
    measurementId: 'G-N535GP9379',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmvxFS6Css8lKttVBC3J_RYQ1R11tHZnc',
    appId: '1:151968151208:android:c3269dc8b5e94e471ff49d',
    messagingSenderId: '151968151208',
    projectId: 'socialfeed-95b3b',
    storageBucket: 'socialfeed-95b3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSY-RofBlfHeo_Vr5xW9Md0uSS08tzXR8',
    appId: '1:151968151208:ios:c89e22eb65eefe111ff49d',
    messagingSenderId: '151968151208',
    projectId: 'socialfeed-95b3b',
    storageBucket: 'socialfeed-95b3b.firebasestorage.app',
    iosBundleId: 'com.example.socialFeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSY-RofBlfHeo_Vr5xW9Md0uSS08tzXR8',
    appId: '1:151968151208:ios:c89e22eb65eefe111ff49d',
    messagingSenderId: '151968151208',
    projectId: 'socialfeed-95b3b',
    storageBucket: 'socialfeed-95b3b.firebasestorage.app',
    iosBundleId: 'com.example.socialFeed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAtVvBbYaaRHIaafeTBJ1NteSSohLyIO4',
    appId: '1:151968151208:web:7f8056248389fd271ff49d',
    messagingSenderId: '151968151208',
    projectId: 'socialfeed-95b3b',
    authDomain: 'socialfeed-95b3b.firebaseapp.com',
    storageBucket: 'socialfeed-95b3b.firebasestorage.app',
    measurementId: 'G-FHP0FJHK4G',
  );
}
